{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafkaConnect.fullname" . }}
  labels:
    {{- include "kafkaConnect.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres.properties: |
    hostname={{ .Values.secrets.postgres.hostname }}
    user={{ .Values.secrets.postgres.user }}
    password={{ .Values.secrets.postgres.password }}
  mysql.properties: |
    hostname={{ .Values.secrets.mysql.hostname }}
    user={{ .Values.secrets.mysql.user }}
    password={{ .Values.secrets.mysql.password }}
{{- end }}
