apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agentflow.fullname" . }}
  labels:
    {{- include "agentflow.labels" . | nindent 4 }}
data:
  tenants.yaml: |
    {{- .Values.config.tenants | nindent 4 }}
  slo.yaml: |
    {{- .Values.config.slo | nindent 4 }}
  pii_fields.yaml: |
    {{- .Values.config.piiFields | nindent 4 }}
  security.yaml: |
    {{- .Values.config.security | nindent 4 }}
  api_versions.yaml: |
    {{- .Values.config.apiVersions | nindent 4 }}
