apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentflow.fullname" . }}
  labels:
    {{- include "agentflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-key: {{ .Values.secrets.adminKey | quote }}
  api_keys.yaml: |
    {{- toYaml .Values.secrets.apiKeys | nindent 4 }}
