"""Measure one module of the CI mutation gate locally, without `mutmut run`.

`.github/workflows/mutation.yml` is the only place the gate has been
measurable: `mutmut run` refuses to start on native Windows (mutmut's
`__main__` calls `sys.exit(1)` at import time), so between weekly runs nobody
here could see a mutation score. This driver produces the same number on this
machine -- minutes, not seconds: one pytest process per mutant, `--jobs` of
them at a time -- by reusing the gate's own pieces instead of reimplementing
them:

* `scripts.mutation_report.MODULE_TARGETS` for the module -> (threshold, tests)
  mapping and `scripts.mutation_report.prepare_workspace` for the workspace,
  so the definition of a target lives in exactly one place;
* `mutmut.mutation.file_mutation.mutate_file_contents` for the mutants, so the
  mutant population is byte-identical to what `mutmut run` would generate;
* plain `pytest` subprocesses to execute them, selected through the
  `MUTANT_UNDER_TEST` environment variable that mutmut's trampoline reads --
  which is what sidesteps the Windows guard.

`mutmut` must be installed (it is in the `dev` extra), but this script never
invokes the `mutmut` CLI.

The number is only worth having if it is about the code in front of you and
comparable to CI's, so two things are load-bearing beyond the mechanism:
a reused workspace is proven to be the one that was asked for (a stamp carrying
the root, the module and digests of the module's source, the whole top-level
package the workspace copies, the target's tests and the `pyproject.toml`
`prepare_workspace` renders the workspace's config from; anything else is
rebuilt), and a mutant that comes back without a verdict is retried once
serially before it is reported as a harness failure -- otherwise a timeout
under `--jobs` makes the score a function of how loaded the machine is.

A workspace is emptied on rebuild, so `--workspace` is resolved to an absolute
path and accepted only when it is not a checkout and carries this driver's own
marker: a `pyproject.toml` marks Python projects in general, this repository
included, and is no evidence that the directory is safe to delete.

Usage:
    python scripts/mutation_local.py --list-modules
    python scripts/mutation_local.py --module serving/semantic_layer/query/sql_builder.py
    python scripts/mutation_local.py --module agentflow/retry.py --only <mutant>,<mutant>

Exits 1 when the module scores below its declared threshold or when any mutant
could not be given a verdict; 0 otherwise.
"""

from __future__ import annotations

import argparse
import concurrent.futures
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts import mutation_report  # noqa: E402

# Written into a throwaway directory that is put on the child processes'
# PYTHONPATH. It must never be shipped as a file inside the repository: a
# sitecustomize.py reachable from the project root is imported by *every*
# interpreter started there, silently changing unrelated runs.
SITECUSTOMIZE_SOURCE = '''\
"""Let a mutmut-generated module import its trampoline on native Windows.

The generated module does `from mutmut.mutation.trampoline import ...`, and
that module imports three names from `mutmut.__main__`. `mutmut/__main__.py`
refuses to run on Windows with `sys.exit(1)` at import time, which kills the
pytest process before a single test runs -- every mutant would then look
"killed" and the score would be a meaningless 100%. Pre-registering a stub for
that one submodule keeps the three names available and never executes the
guard.

Generated by scripts/mutation_local.py; not part of the repository.
"""

import sys
import types

try:
    import mutmut
except Exception:  # pragma: no cover - mutmut simply is not installed
    pass
else:
    if "mutmut.__main__" not in sys.modules:

        class MutmutProgrammaticFailException(Exception):
            pass

        def mangled_name_from_mutant_name(mutant_name: str) -> str:
            assert "__mutmut_" in mutant_name, mutant_name
            return mutant_name.partition("__mutmut_")[0]

        def record_trampoline_hit(name, caller=None):
            """Only mutmut's `stats` pass records hits; this driver never runs it."""

        stub = types.ModuleType("mutmut.__main__")
        stub.MutmutProgrammaticFailException = MutmutProgrammaticFailException
        stub.mangled_name_from_mutant_name = mangled_name_from_mutant_name
        stub.record_trampoline_hit = record_trampoline_hit
        sys.modules["mutmut.__main__"] = stub
        mutmut.__main__ = stub
'''

# Only these two are verdicts. pytest's remaining exit codes (2 = internal
# error / interrupted, 3 = internal error, 4 = usage, 5 = no tests collected)
# mean the harness failed, not that the mutant lived or died, and a timeout
# gets no exit code at all.
SURVIVED_EXIT_CODE = 0
KILLED_EXIT_CODE = 1

BACKUP_SUFFIX = ".mutation-local-orig"
REPORT_FILENAME = "mutation-local-report.json"
STAMP_FILENAME = "mutation-local-stamp.json"
SCRATCH_DIRNAME = ".mutation-local-tmp"

# Dropped into a workspace the moment this driver starts building one, and the
# only thing that makes a directory eligible to be emptied later. It has to be
# written before `prepare_workspace` rather than with the stamp afterwards, so
# that a prepare killed halfway still leaves a directory the next run may
# rebuild instead of one it has to refuse.
MARKER_FILENAME = ".mutation-local-workspace"
MARKER_TEXT = (
    "Built by scripts/mutation_local.py. Everything in this directory is\n"
    "deleted and rebuilt whenever the driver's stamp stops matching. Do not\n"
    "keep anything here.\n"
)


@dataclass
class ModuleRun:
    """Outcome of measuring one module."""

    module_path: Path
    threshold: float
    generated: int
    killed: list[str] = field(default_factory=list)
    survived: list[str] = field(default_factory=list)
    errored: list[tuple[str, int | None]] = field(default_factory=list)
    retried: list[str] = field(default_factory=list)

    def record(self, mutant_name: str, exit_code: int | None) -> None:
        """File one mutant under the verdict its exit code carries."""
        verdict = classify_exit_code(exit_code)
        if verdict == "survived":
            self.survived.append(mutant_name)
        elif verdict == "killed":
            self.killed.append(mutant_name)
        else:
            self.errored.append((mutant_name, exit_code))

    @property
    def scored(self) -> int:
        return len(self.killed) + len(self.survived)

    @property
    def score(self) -> float:
        return len(self.killed) / self.scored if self.scored else 0.0

    @property
    def passed(self) -> bool:
        return bool(self.scored) and not self.errored and self.score >= self.threshold


def classify_exit_code(exit_code: int | None) -> str:
    """Map a pytest exit code onto a mutant verdict.

    0 means the tests passed with the mutant active, i.e. nothing noticed the
    change: the mutant survived. 1 means at least one test failed: killed.
    Anything else -- including a timeout, which arrives as None -- is a harness
    failure and must never be counted as a kill.
    """
    if exit_code == SURVIVED_EXIT_CODE:
        return "survived"
    if exit_code == KILLED_EXIT_CODE:
        return "killed"
    return "errored"


def dotted_module(module_path: Path) -> str:
    """`serving/api/rate_limiter.py` -> `serving.api.rate_limiter`.

    Mutant names are `<dotted module>.<mutant>`; the workspace mutates each
    module under a top-level package name, so the repo-relative key from
    MODULE_TARGETS is already the import path.
    """
    return ".".join(module_path.with_suffix("").parts)


def write_source(path: Path, text: str) -> None:
    """Write a source file without newline translation.

    The repository is LF; the default text mode on Windows would hand the
    module back as CRLF, and on a symlinked workspace that lands in the working
    tree as a diff nobody asked for.
    """
    path.write_text(text, encoding="utf-8", newline="")


def write_sitecustomize(directory: Path) -> Path:
    """Generate the trampoline shim into `directory` and return that directory."""
    directory.mkdir(parents=True, exist_ok=True)
    write_source(directory / "sitecustomize.py", SITECUSTOMIZE_SOURCE)
    return directory


def child_env(shim_dir: Path, mutant: str | None = None) -> dict[str, str]:
    env = dict(os.environ)
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = str(shim_dir) + (os.pathsep + existing if existing else "")
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    if mutant is not None:
        env["MUTANT_UNDER_TEST"] = mutant
    else:
        env.pop("MUTANT_UNDER_TEST", None)
    return env


def materialize_package(workspace: Path, module_path: Path) -> bool:
    """Replace the workspace's symlinked top-level package with a real copy.

    `prepare_workspace` symlinks `serving` / `agentflow` at the real sources.
    This driver overwrites the module file with each mutated version, so
    through a symlink every write would land in the working tree. Returns True
    when a copy was made.
    """
    top = workspace / module_path.parts[0]
    if not top.is_symlink():
        return False
    real = top.resolve()
    top.unlink()
    shutil.copytree(real, top)
    return True


def source_package_dir(module_path: Path) -> Path:
    """The checkout directory `prepare_workspace` mounts as the top-level package.

    The MODULE_TARGETS keys are workspace-relative (`serving/...`,
    `agentflow/...`) because those two packages are mounted at the top level;
    this is the same mapping read backwards, so the driver can look at the real
    sources before it decides whether an existing workspace is still about them.
    """
    root = mutation_report.ROOT
    top = module_path.parts[0]
    if top == "agentflow":
        return root / "sdk" / "agentflow"
    if top == "serving":
        return root / "src" / "agentflow_runtime" / "serving"
    return root / top


def source_module_file(module_path: Path) -> Path:
    """Where a MODULE_TARGETS key lives in the checkout it is measured from."""
    return source_package_dir(module_path).joinpath(*module_path.parts[1:])


def tree_sha256(directory: Path) -> str:
    """Digest of every source file under `directory`, path names included.

    Byte-compiled leftovers are skipped: they follow the sources they came from
    and would otherwise make a workspace look stale on a machine that imported
    the package once.
    """
    digest = hashlib.sha256()
    for path in sorted(directory.rglob("*")):
        if "__pycache__" in path.parts or path.suffix == ".pyc" or not path.is_file():
            continue
        digest.update(path.relative_to(directory).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
        digest.update(b"\0")
    return digest.hexdigest()


def path_sha256(path: Path) -> str:
    if path.is_dir():
        return tree_sha256(path)
    if path.is_file():
        return hashlib.sha256(path.read_bytes()).hexdigest()
    return "missing"


def workspace_stamp(module_path: Path, target: mutation_report.ModuleTarget) -> dict[str, str]:
    """What a workspace must have been built from for reusing it to be honest.

    Root and module because a workspace keyed only on the module's stem is
    reused across `--root` checkouts and across same-named modules. The digests
    because the tool's whole point is "run it before you commit": the workspace
    holds a *real copy* of the whole top-level package (see
    `materialize_package`), so keying on the target module's own file alone
    would let an edit to any sibling -- or to the tests that do the killing --
    be measured against the previous run's copy of it. `pyproject.toml` for the
    same reason: `prepare_workspace` renders the workspace's copy from the
    checkout's, always as a real file, so pytest addopts, filterwarnings, plugin
    toggles and `[tool.mutmut]` all reach the run through a copy that would
    otherwise go stale silently.

    What `prepare_workspace` symlinks is live by construction and needs no
    digest. Where the OS refuses symlinks it copies the linked trees instead
    (`src`/`sdk`, `tests`, `config`, `scripts`); those copies are not digested
    -- on a machine with symlinks they are links and hashing them every run
    would be pure cost -- so on such a machine an edit to `src`/`sdk`,
    `config`, `scripts` or to the rest of `tests` beyond the target's own test
    files (which `tests_sha256` covers everywhere) needs a fresh `--workspace`.
    """
    source = source_module_file(module_path)
    if not source.is_file():
        raise SystemExit(f"module source not found: {source}")
    tests_digest = hashlib.sha256()
    for test_path in target.tests:
        tests_digest.update(test_path.encode("utf-8"))
        tests_digest.update(b"\0")
        tests_digest.update(path_sha256(mutation_report.ROOT / test_path).encode("utf-8"))
        tests_digest.update(b"\0")
    return {
        "root": mutation_report.ROOT.as_posix(),
        "module": module_path.as_posix(),
        "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
        "package_sha256": tree_sha256(source_package_dir(module_path)),
        "tests_sha256": tests_digest.hexdigest(),
        "pyproject_sha256": path_sha256(mutation_report.ROOT / "pyproject.toml"),
    }


def read_stamp(path: Path) -> dict[str, str] | None:
    """The stamp `path` carries, or None if there is none to trust."""
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return loaded if isinstance(loaded, dict) else None


def describe_stamp(stamp: dict[str, str]) -> str:
    return (
        f"  {stamp['module']} from {stamp['root']} "
        f"(source sha256 {stamp['source_sha256'][:12]}, "
        f"package sha256 {stamp['package_sha256'][:12]})"
    )


def remove_workspace_entry(entry: Path) -> None:
    """Delete one workspace entry without ever following a link out of it.

    `prepare_workspace` symlinks `tests`, `config`, `scripts`, ... at the real
    checkout -- `os.symlink` only, never a junction. `shutil.rmtree` refuses to
    descend a directory symlink on Windows and following one would delete the
    checkout, so links are unlinked as links, which on Windows means `rmdir`
    when they point at a directory.
    """
    if entry.is_symlink():
        try:
            entry.unlink()
        except OSError:
            entry.rmdir()
        return
    if entry.is_dir():
        shutil.rmtree(entry)
        return
    entry.unlink(missing_ok=True)


def check_workspace_location(workspace: Path) -> None:
    """Refuse a `--workspace` that is a checkout rather than a scratch directory.

    A rebuild empties the directory, so the two shapes that would cost real
    work are refused before anything is deleted: a path inside the checkout the
    sources come from (`--workspace .` typed in a repository root is the whole
    reason this exists), and any directory carrying a `.git`.
    """
    resolved = workspace.resolve()
    for checkout in {ROOT, Path(mutation_report.ROOT).resolve()}:
        if resolved == checkout or checkout in resolved.parents:
            raise SystemExit(
                f"refusing to use {resolved} as a workspace: it is the checkout {checkout} "
                "or lives inside it -- pass a --workspace outside the repository"
            )
    if (resolved / ".git").exists():
        raise SystemExit(
            f"refusing to use {resolved} as a workspace: it holds a .git, so it is a "
            "checkout -- pass a --workspace outside the repository"
        )


def clear_workspace(workspace: Path) -> None:
    """Empty `workspace` so it can be rebuilt from the sources actually asked for.

    A rebuild deletes everything in there, and `--workspace` is a path the
    caller types, so only a directory carrying this driver's own marker or
    stamp is emptied. A `pyproject.toml` is not a marker of a workspace built
    here: it is a marker of Python projects generally, this repository
    included, which is exactly the wrong value to accept.
    """
    check_workspace_location(workspace)
    if not workspace.is_dir():
        return
    entries = sorted(workspace.iterdir())
    ours = (workspace / MARKER_FILENAME).exists() or (workspace / STAMP_FILENAME).exists()
    if entries and not ours:
        raise SystemExit(
            f"refusing to rebuild {workspace}: it is not empty and holds no mutation-local "
            "workspace -- pass a --workspace of its own"
        )
    for entry in entries:
        remove_workspace_entry(entry)


def measure_covered_lines(
    workspace: Path,
    module_file: Path,
    tests: tuple[str, ...],
    *,
    python: str,
    shim_dir: Path,
) -> set[int]:
    """Line numbers of `module_file` executed by `tests`.

    `mutate_only_covered_lines = true` is set in `[tool.mutmut]`, so the mutant
    population -- and therefore the mutant numbering -- depends on coverage.
    Skipping this step produces mutants CI never generated.
    """
    data_file = workspace / ".coverage-mutation-local"
    data_file.unlink(missing_ok=True)
    command = [
        python,
        "-m",
        "coverage",
        "run",
        f"--data-file={data_file}",
        f"--include={module_file.as_posix()}",
        "-m",
        "pytest",
        "-q",
        "-p",
        "no:cacheprovider",
        *tests,
    ]
    result = subprocess.run(
        command,
        cwd=workspace,
        env=child_env(shim_dir),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        print(result.stdout[-4000:])
        print(result.stderr[-2000:], file=sys.stderr)
        raise SystemExit(f"baseline test run failed (exit {result.returncode})")

    from coverage import CoverageData

    coverage_data = CoverageData(basename=str(data_file))
    coverage_data.read()
    for measured in coverage_data.measured_files():
        if Path(measured).resolve() == module_file.resolve():
            return set(coverage_data.lines(measured) or [])
    raise SystemExit(f"coverage recorded no lines for {module_file}")


def generate_mutants(module_path: Path, source: str, covered_lines: set[int]) -> Any:
    """Mutants for `source`, straight from the engine `mutmut run` uses.

    Imported lazily so the driver's own unit tests can stub this out without
    mutmut installed -- and so `--list-modules` works without it too.
    """
    from mutmut.mutation.file_mutation import mutate_file_contents

    return mutate_file_contents(module_path.as_posix(), source, covered_lines)


def run_mutant(
    workspace: Path,
    tests: tuple[str, ...],
    mutant_name: str,
    *,
    python: str,
    shim_dir: Path,
    basetemp: Path,
    timeout: float,
) -> tuple[str, int | None]:
    """Run `tests` with one mutant active; return its pytest exit code.

    Each mutant gets its own `--basetemp`: pytest wipes and recreates that
    directory at startup, so concurrent runs sharing one abort each other and
    exit 2.
    """
    command = [
        python,
        "-m",
        "pytest",
        "-x",
        "-q",
        "--no-header",
        "-p",
        "no:cacheprovider",
        f"--basetemp={basetemp}",
        *tests,
    ]
    try:
        result = subprocess.run(
            command,
            cwd=workspace,
            env=child_env(shim_dir, mutant_name),
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return mutant_name, None
    return mutant_name, result.returncode


def retry_missing_verdicts(
    run: ModuleRun,
    workspace: Path,
    tests: tuple[str, ...],
    *,
    python: str,
    shim_dir: Path,
    scratch: Path,
    timeout: float,
) -> None:
    """Give every mutant that came back without a verdict one serial retry.

    A timeout is not a verdict and must never be counted as a kill -- but under
    `--jobs` it usually says more about the machine than about the mutant: at
    six concurrent pytest processes four sql_builder mutants CI kills hit the
    parallel timeout here and cost the run 0.4 points. One uncontended second
    chance, with a longer timeout, removes contention as the explanation.
    Whatever still has no verdict afterwards is the harness failure it looks
    like, and is reported as one.
    """
    pending = list(run.errored)
    run.errored = []
    print(
        f"no verdict for {len(pending)} mutant(s) in the parallel pass -- "
        f"retrying serially (timeout {timeout:.0f}s)",
        flush=True,
    )
    for index, (mutant_name, _) in enumerate(pending):
        _, exit_code = run_mutant(
            workspace,
            tests,
            mutant_name,
            python=python,
            shim_dir=shim_dir,
            basetemp=scratch / f"retry{index}",
            timeout=timeout,
        )
        run.retried.append(mutant_name)
        run.record(mutant_name, exit_code)


def measure_module(
    module_path: Path,
    target: mutation_report.ModuleTarget,
    workspace: Path,
    shim_dir: Path,
    *,
    python: str,
    jobs: int,
    timeout: float,
    retry_timeout: float | None = None,
    only: set[str] | None = None,
) -> ModuleRun:
    """Prepare or reuse a workspace, generate the mutants, and run them all."""
    if retry_timeout is None:
        retry_timeout = timeout * 3

    check_workspace_location(workspace)
    stamp = workspace_stamp(module_path, target)
    stamp_path = workspace / STAMP_FILENAME
    # A previous run killed mid-flight would leave the module mutated; the
    # pristine copy taken when the workspace was built is what it is restored
    # from, so a reused workspace never mutates a mutant.
    backup = workspace / f"{module_path.stem}{BACKUP_SUFFIX}"
    reusable = (
        read_stamp(stamp_path) == stamp
        and (workspace / "pyproject.toml").exists()
        and backup.exists()
    )
    if reusable:
        print(f"workspace reused: {workspace}")
    else:
        # Anything else -- a workspace left by a different --root, by another
        # module, by the edit made since, or by a prepare that never finished
        # -- gets rebuilt. Reusing it would report a number about sources
        # nobody asked for, and a green that predates your change is worse than
        # no number at all.
        clear_workspace(workspace)
        workspace.mkdir(parents=True, exist_ok=True)
        write_source(workspace / MARKER_FILENAME, MARKER_TEXT)
        mutation_report.prepare_workspace(workspace, module_path, target)
        print(f"workspace prepared: {workspace}")
    print(describe_stamp(stamp))
    materialize_package(workspace, module_path)

    module_file = workspace / module_path
    if not backup.exists():
        write_source(backup, module_file.read_text(encoding="utf-8"))
    source = backup.read_text(encoding="utf-8")
    write_source(module_file, source)
    if not reusable:
        # Stamped only now the workspace is complete, pristine copy included:
        # an interrupted prepare must not leave a stamp the next run believes.
        write_source(stamp_path, json.dumps(stamp, indent=2) + "\n")

    started = time.monotonic()
    covered = measure_covered_lines(
        workspace, module_file, target.tests, python=python, shim_dir=shim_dir
    )
    print(f"covered lines: {len(covered)} ({time.monotonic() - started:.1f}s)")

    mutated = generate_mutants(module_path, source, covered)
    names = list(mutated.mutant_names)
    print(f"generated mutants: {len(names)}")

    dotted = dotted_module(module_path)
    selected = names
    if only is not None:
        # The engine names mutants `x__mutmut_2`; everything this driver prints
        # -- the survivor list and the JSON report -- carries the dotted module
        # in front. A name copied out of that report has to select the mutant it
        # names, so the prefix is stripped when it is there and both spellings
        # are accepted.
        prefix = f"{dotted}."
        wanted = {name.removeprefix(prefix) for name in only}
        selected = [name for name in names if name in wanted]
        missing = wanted - set(selected)
        if missing:
            print(f"not generated (ignored): {sorted(prefix + name for name in missing)}")

    run = ModuleRun(module_path=module_path, threshold=target.threshold, generated=len(names))
    # pytest wipes and recreates its `--basetemp` at startup, so the scratch is
    # namespaced per invocation on top of per mutant: a workspace whose stamp
    # matches is deliberately shared, and two runs of the same module -- the
    # command typed in a second terminal -- would otherwise hand pytest the same
    # `mutant<N>` directories and abort each other out of a verdict.
    scratch = workspace / SCRATCH_DIRNAME / f"run-{os.getpid()}-{uuid.uuid4().hex[:8]}"
    write_source(module_file, mutated.code)
    started = time.monotonic()
    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as pool:
            futures = [
                pool.submit(
                    run_mutant,
                    workspace,
                    target.tests,
                    f"{dotted}.{mutant}",
                    python=python,
                    shim_dir=shim_dir,
                    basetemp=scratch / f"mutant{index}",
                    timeout=timeout,
                )
                for index, mutant in enumerate(selected)
            ]
            for done, future in enumerate(concurrent.futures.as_completed(futures), start=1):
                run.record(*future.result())
                if done % 20 == 0 or done == len(selected):
                    elapsed = time.monotonic() - started
                    print(f"  {done}/{len(selected)} ({elapsed:.0f}s)", flush=True)
        if run.errored:
            retry_missing_verdicts(
                run,
                workspace,
                target.tests,
                python=python,
                shim_dir=shim_dir,
                scratch=scratch,
                timeout=retry_timeout,
            )
    finally:
        # Always hand the workspace back unmutated, including on Ctrl-C.
        write_source(module_file, source)
        # This invocation's scratch is nobody else's to read, and a reused
        # workspace would otherwise collect one tree per run.
        shutil.rmtree(scratch, ignore_errors=True)
    return run


def report_payload(run: ModuleRun) -> dict:
    return {
        "module": run.module_path.as_posix(),
        "threshold": run.threshold,
        "score": run.score,
        "generated": run.generated,
        "killed": len(run.killed),
        "survived": sorted(run.survived),
        "errored": [[name, code] for name, code in sorted(run.errored)],
        "retried": sorted(run.retried),
        "passed": run.passed,
    }


def print_report(run: ModuleRun) -> None:
    print()
    print(
        f"{run.module_path.name}: score={run.score:.1%} threshold={run.threshold:.0%} "
        f"(killed={len(run.killed)}, survived={len(run.survived)})"
    )
    for mutant_name in sorted(run.survived):
        print(f"    - {mutant_name}")
    if run.retried:
        print(f"  {len(run.retried)} mutant(s) had no verdict in parallel; retried serially")
    if run.errored:
        print(f"  no verdict for {len(run.errored)} mutant(s) -- harness failure, not a kill:")
        for mutant_name, exit_code in sorted(run.errored):
            print(f"    ! {mutant_name} exit={'timeout' if exit_code is None else exit_code}")


def default_workspace(module_path: Path) -> Path:
    # Outside the repository: the workspace holds a full copy of the mutated
    # package plus pytest scratch directories. Keyed on the module's stem, so a
    # different --root or a different module lands on the same path -- which is
    # exactly what the stamp check in `measure_module` is there to catch.
    return Path(tempfile.gettempdir()) / "agentflow-mutation-local" / module_path.stem


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Measure the CI mutation gate for one module locally, using mutmut's "
            "mutation engine but plain pytest subprocesses (no `mutmut run`)."
        ),
    )
    parser.add_argument(
        "--module",
        help="MODULE_TARGETS key, e.g. serving/semantic_layer/query/sql_builder.py",
    )
    parser.add_argument(
        "--list-modules",
        action="store_true",
        help="print the gate's modules with their thresholds and exit",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="checkout to build the workspace from (default: this script's repository)",
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=None,
        help=(
            "where to build the workspace (default: a temp directory). Resolved to an "
            "absolute path, rebuilt (emptied) unless its stamp matches this root, "
            "module, package tree, tests and pyproject.toml, and refused outright when "
            "it is a checkout"
        ),
    )
    parser.add_argument(
        "--only",
        default=None,
        help="comma-separated mutant names to run, bare or as printed (`<module>.<mutant>`)",
    )
    parser.add_argument("--jobs", type=int, default=4, help="concurrent pytest processes")
    parser.add_argument(
        "--timeout",
        type=float,
        default=300.0,
        help="seconds a single mutant may run before it is reported as errored",
    )
    parser.add_argument(
        "--retry-timeout",
        type=float,
        default=None,
        help=(
            "seconds for the serial second chance given to a mutant that came back "
            "without a verdict (default: 3x --timeout)"
        ),
    )
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="interpreter for the child pytest runs (default: the current one)",
    )
    parser.add_argument(
        "--json",
        type=Path,
        default=None,
        help=f"write the JSON report here (default: <workspace>/{REPORT_FILENAME})",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    if args.list_modules:
        for declared_path, declared in mutation_report.MODULE_TARGETS.items():
            print(f"{declared_path.as_posix()}  threshold={declared.threshold:.0%}")
        return 0
    if not args.module:
        print("--module is required (see --list-modules)", file=sys.stderr)
        return 2

    module_path = Path(args.module)
    target: mutation_report.ModuleTarget | None = mutation_report.MODULE_TARGETS.get(module_path)
    if target is None:
        print(f"unknown module: {args.module} (see --list-modules)", file=sys.stderr)
        return 2

    if args.root is not None:
        # MODULE_TARGETS still comes from this checkout; only the sources the
        # workspace is built from move.
        mutation_report.ROOT = Path(args.root).resolve()

    # Resolved before anything reads it: `module_file` inherits this path, and a
    # relative one turns into a `--include=` pattern coverage never matches
    # against the absolute paths it records -- the module then measures as
    # uncovered, with an error message about the wrong thing.
    workspace = Path(args.workspace or default_workspace(module_path)).resolve()
    only = None
    if args.only:
        only = {name.strip() for name in args.only.split(",") if name.strip()}

    with tempfile.TemporaryDirectory(prefix="agentflow-mutation-shim-") as shim_root:
        shim_dir = write_sitecustomize(Path(shim_root))
        run = measure_module(
            module_path,
            target,
            workspace,
            shim_dir,
            python=args.python,
            jobs=max(1, args.jobs),
            timeout=args.timeout,
            retry_timeout=args.retry_timeout,
            only=only,
        )

    print_report(run)
    report_path = args.json or workspace / REPORT_FILENAME
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(
        json.dumps(report_payload(run), indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"report: {report_path}")
    return 0 if run.passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
