"""Every catalog metric must carry a versioned contract with matching lineage.

config/contracts/metric.*.v1.yaml are generated by scripts/generate_contracts.py;
this suite pins the generated contracts against the DataCatalog declarations so
the two sources of the event->metric graph cannot drift apart.
"""

from __future__ import annotations

from src.serving.semantic_layer.catalog import DataCatalog
from src.serving.semantic_layer.contract_registry import ContractRegistry

METRIC_NAMES = (
    "revenue",
    "order_count",
    "avg_order_value",
    "conversion_rate",
    "active_sessions",
    "error_rate",
)


def _registry() -> ContractRegistry:
    registry = ContractRegistry()
    registry.load()
    return registry


def test_every_catalog_metric_has_a_stable_v1_contract():
    registry = _registry()

    for name in METRIC_NAMES:
        contract = registry.get_contract(f"metric.{name}", "1")
        assert contract is not None, f"metric.{name} has no v1 contract"
        assert contract.status == "stable"


def test_catalog_picks_up_the_contract_version_for_every_metric():
    catalog = DataCatalog()

    for name in METRIC_NAMES:
        assert catalog.metrics[name].contract_version == "1", name


def test_contract_lineage_matches_the_catalog():
    registry = _registry()
    catalog = DataCatalog()

    for name in METRIC_NAMES:
        contract = registry.get_contract(f"metric.{name}", "1")
        metric = catalog.metrics[name]
        assert set(contract.source_events) == set(metric.source_events), name
        assert contract.source_table == metric.source_table, name


def test_contract_value_unit_matches_the_catalog_unit():
    registry = _registry()
    catalog = DataCatalog()

    for name in METRIC_NAMES:
        contract = registry.get_contract(f"metric.{name}", "1")
        value_field = contract.field_map()["value"]
        assert value_field.unit == catalog.metrics[name].unit, name


def test_metric_contracts_declare_a_freshness_budget():
    registry = _registry()

    for name in METRIC_NAMES:
        contract = registry.get_contract(f"metric.{name}", "1")
        assert contract.freshness is not None, name
        budget = contract.freshness["p95_staleness_budget_seconds"]
        assert budget > 0, name
        assert "freshness-benchmark" in contract.freshness["basis"], name


def test_contract_to_dict_exposes_lineage_additively():
    registry = _registry()

    metric_payload = registry.get_contract("metric.revenue", "1").to_dict()
    assert metric_payload["source_events"] == [
        "order.created",
        "order.updated",
        "order.cancelled",
    ]
    assert metric_payload["source_table"] == "orders_v2"
    assert metric_payload["freshness"]["p95_staleness_budget_seconds"] == 2.5

    # Entity contracts predate lineage and must keep their payload unchanged.
    order_payload = registry.get_contract("order", "2").to_dict()
    assert "source_events" not in order_payload
    assert "source_table" not in order_payload
    assert "freshness" not in order_payload
