from __future__ import annotations

import re
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FLINK_DIR = PROJECT_ROOT / "src" / "agentflow_runtime" / "processing" / "flink_jobs"
FLINK_MANIFEST = FLINK_DIR / "requirements.txt"
FLINK_LOCK = FLINK_DIR / "flink-requirements.lock"
FLINK_DOCKERFILE = FLINK_DIR / "Dockerfile"
SECURITY_WORKFLOW = PROJECT_ROOT / ".github" / "workflows" / "security.yml"

FLINK_MANIFEST_REL = "src/agentflow_runtime/processing/flink_jobs/requirements.txt"
FLINK_LOCK_REL = "src/agentflow_runtime/processing/flink_jobs/flink-requirements.lock"
SAFETY_OUTPUT_DIR = 'output_dir = root / ".artifacts" / "security" / "safety"'
SAFETY_FLINK_TARGET = 'output_dir / "requirements-flink-runtime.txt"'


def _normalise_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _locked_packages() -> dict[str, int]:
    text = FLINK_LOCK.read_text(encoding="utf-8")
    packages: dict[str, int] = {}
    current: str | None = None

    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if line == stripped:
            assert stripped.endswith("\\"), f"locked requirement lacks hashes: {stripped}"
            requirement = stripped[:-1].rstrip()
            match = re.fullmatch(r"([A-Za-z0-9][A-Za-z0-9_.-]*)==([^\s;\\]+)", requirement)
            assert match is not None, f"requirement is not an exact pin: {requirement}"
            current = _normalise_name(match.group(1))
            assert current not in packages, f"duplicate locked package: {current}"
            packages[current] = 0
            continue

        assert current is not None, f"lock option has no requirement: {stripped}"
        assert re.fullmatch(r"--hash=sha256:[0-9a-f]{64}(?: \\)?", stripped), stripped
        packages[current] += 1

    assert packages, "Flink lock resolved to zero packages"
    assert all(count > 0 for count in packages.values())
    return packages


def _security_inventory_script() -> str:
    workflow = yaml.safe_load(SECURITY_WORKFLOW.read_text(encoding="utf-8"))
    step = next(
        step
        for step in workflow["jobs"]["safety"]["steps"]
        if step.get("name") == "Resolve Safety dependency inputs"
    )
    return step["run"]


def test_flink_lock_is_stable_hash_pinned_uv_output() -> None:
    text = FLINK_LOCK.read_text(encoding="utf-8")
    header = "\n".join(text.splitlines()[:6])

    assert "This file was autogenerated by uv" in header
    assert f"uv pip compile {FLINK_MANIFEST_REL}" in header
    assert "--generate-hashes" in header
    assert "--python-version 3.12" in header
    assert "--python-platform x86_64-manylinux_2_39" in header
    assert "/tmp/" not in header  # noqa: S108 - asserts the lock header has no tmp path

    locked = _locked_packages()
    manifest_names = {
        _normalise_name(match.group(1))
        for line in FLINK_MANIFEST.read_text(encoding="utf-8").splitlines()
        if (match := re.match(r"^([A-Za-z0-9][A-Za-z0-9_.-]*)", line))
    }
    assert manifest_names <= locked.keys()
    assert "apache-flink==2.3.0" in text


def test_flink_image_installs_only_the_hash_pinned_lock() -> None:
    text = FLINK_DOCKERFILE.read_text(encoding="utf-8")

    assert f"COPY {FLINK_LOCK_REL.removeprefix('src/')} /tmp/flink-requirements.lock" in text
    assert "--require-hashes -r /tmp/flink-requirements.lock" in text
    assert "-r /tmp/flink-requirements.txt" not in text
    assert "version('apache-flink')" in text
    assert "assert v == '${FLINK_VERSION}'" in text


def test_safety_uses_the_lock_as_authoritative_flink_input() -> None:
    script = _security_inventory_script()
    flink_start = script.index("# The Flink runtime")
    flink_end = script.index("summary_path", flink_start)
    flink_block = script[flink_start:flink_end]

    assert FLINK_MANIFEST_REL in script
    assert FLINK_LOCK_REL in flink_block
    assert SAFETY_OUTPUT_DIR in script
    assert SAFETY_FLINK_TARGET in flink_block
    assert "copy_locked_requirements(" in flink_block
    assert "resolve_requirements(" not in flink_block
    assert "def copy_locked_requirements(" in script
    assert "shutil.copyfile(source, target)" in script
