from __future__ import annotations

from pathlib import Path

import pytest

from scripts.check_archive_provenance import (
    REQUIRED_FIELDS,
    check_archive_provenance,
    is_archived_document,
    load_tracked_paths,
    main,
    original_path_value,
)

ROOT = Path(__file__).resolve().parents[2]

SHAPE_BLOCKQUOTE_LIST = """\
# Archived API DuckDB E22 non-target scratch rehearsal

> **Archive metadata**
>
> - Original path: *docs/operations/api-duckdb-non-target-scratch-rehearsal-runbook.md*
> - Archived: 2026-08-27
> - Reason: E22 is a consumed transport-blocked identity; the three scratch
>   variants were consolidated behind one identity-neutral current guide
> - Current replacement:
>   [current non-target scratch rehearsal](../../operations/api-duckdb-non-target-scratch-rehearsal-runbook.md)
> - Content type: immutable operational execution record
>
> The runbook body below is unchanged; only this provenance block was added.
"""

SHAPE_PLAIN_BLOCKQUOTE = """\
# Archived S8 real-path freshness benchmark — 2026-07-09

> Original path: *docs/perf/freshness-e2e-realpath.md*
>
> Archived on: 2026-08-29
>
> Content type: historical generated S8 real-path freshness snapshot
>
> Provenance: generated by `scripts/benchmark_freshness_e2e.py`; measured
> `2026-07-09T15:33:39.729745+00:00` on the single-node Mac/Colima stand
> recorded in the preserved body below.
>
> Reason: the undated path is now the stable artifact-lifecycle reference;
> new host/time-dependent runs write ignored `.artifacts/freshness/` outputs
> and require a new dated evidence identity before promotion.
>
> The body below is preserved byte-for-byte from Git blob
> `8332dc9d430c0c2e51d6756c21892d827b6f1ecf`.
"""

SHAPE_PLAIN_LIST = """\
# Archived first draft: OpsLab transfer plan

- Original location: `plan_26_08_2026.md`
- Archived: 2026-08-26
- Reason: the first interpretation treated OpsLab as the main roadmap instead
  of optimizing the real AgentFlow Runtime documentation corpus
- Replacement: [`plan_26_08_2026.md`](../../../plan_26_08_2026.md)
- Content type: superseded planning narrative

The text below is preserved as committed in `fff2dd3`.
"""

_FIELD_LINES = {
    "original_path": "- Original path: docs/example.md",
    "archived_on": "- Archived: 2026-08-26",
    "reason": "- Reason: moved for hygiene",
    "replacement": "- Current replacement: docs/current.md",
    "content_type": "- Content type: historical narrative",
}


def _write(root: Path, relative: str, body: str) -> None:
    path = root.joinpath(*relative.split("/"))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8", newline="\n")


def _complete_header(*fields: str) -> str:
    lines = ["# Fixture", ""]
    lines.extend(_FIELD_LINES[field] for field in fields)
    lines.append("")
    return "\n".join(lines)


def test_real_archive_tree_has_provenance() -> None:
    assert check_archive_provenance(ROOT) == []
    tracked = load_tracked_paths(ROOT)
    assert tracked is not None
    archived = [path for path in tracked if is_archived_document(path)]
    assert len(archived) >= 17


@pytest.mark.parametrize(
    ("path", "expected"),
    [
        ("docs/archive/operations/note.md", True),
        ("docs/archive/README.md", False),
        ("docs/archive/product/README.md", False),
        ("docs/perf/x.md", False),
        ("docs/archive/notes.txt", False),
    ],
)
def test_is_archived_document_truth_table(path: str, expected: bool) -> None:
    assert is_archived_document(path) is expected


@pytest.mark.parametrize("field", list(REQUIRED_FIELDS))
def test_missing_required_field_is_reported(tmp_path: Path, field: str) -> None:
    relative = "docs/archive/missing.md"
    kept = tuple(name for name in REQUIRED_FIELDS if name != field)
    _write(tmp_path, relative, _complete_header(*kept))
    labels = ", ".join(sorted(REQUIRED_FIELDS[field]))
    assert check_archive_provenance(tmp_path, tracked_paths={relative}) == [
        f"{relative}: missing {field} (expected one of: {labels})"
    ]


def test_archived_on_without_iso_date_is_reported(tmp_path: Path) -> None:
    relative = "docs/archive/dateless.md"
    _write(
        tmp_path,
        relative,
        _complete_header(
            "original_path",
            "reason",
            "replacement",
            "content_type",
        ).replace(
            "- Reason:",
            "- Archived: last week\n- Reason:",
        ),
    )
    assert check_archive_provenance(tmp_path, tracked_paths={relative}) == [
        f"{relative}: archived_on has no ISO date"
    ]


def test_provenance_after_header_window_is_reported(tmp_path: Path) -> None:
    relative = "docs/archive/late.md"
    filler = "\n".join(f"padding line {index}" for index in range(1, 41))
    _write(tmp_path, relative, f"{filler}\n{_complete_header(*REQUIRED_FIELDS)}")
    problems = check_archive_provenance(tmp_path, tracked_paths={relative})
    assert problems
    assert all(problem.startswith(f"{relative}: missing ") for problem in problems)
    assert len(problems) == len(REQUIRED_FIELDS)


def test_archive_readme_index_is_ignored(tmp_path: Path) -> None:
    readme = "docs/archive/README.md"
    nested = "docs/archive/product/README.md"
    valid = "docs/archive/kept.md"
    _write(tmp_path, readme, "# Index\n")
    _write(tmp_path, nested, "# Nested index\n")
    _write(tmp_path, valid, _complete_header(*REQUIRED_FIELDS))
    tracked = {readme, nested, valid}
    assert check_archive_provenance(tmp_path, tracked_paths=tracked) == []


@pytest.mark.parametrize(
    ("relative", "body", "also_tracked"),
    [
        ("docs/archive/shape-blockquote-list.md", SHAPE_BLOCKQUOTE_LIST, frozenset()),
        (
            "docs/archive/shape-plain-blockquote.md",
            SHAPE_PLAIN_BLOCKQUOTE,
            # Shape 2 carries no replacement label: its undated original path is
            # the living replacement, so it must still be tracked.
            frozenset({"docs/perf/freshness-e2e-realpath.md"}),
        ),
        ("docs/archive/shape-plain-list.md", SHAPE_PLAIN_LIST, frozenset()),
    ],
)
def test_real_world_header_shapes_pass(
    tmp_path: Path, relative: str, body: str, also_tracked: frozenset[str]
) -> None:
    _write(tmp_path, relative, body)
    tracked = {relative, *also_tracked}
    assert check_archive_provenance(tmp_path, tracked_paths=tracked) == []


def test_plain_blockquote_shape_fails_when_original_path_is_gone(tmp_path: Path) -> None:
    relative = "docs/archive/shape-plain-blockquote.md"
    _write(tmp_path, relative, SHAPE_PLAIN_BLOCKQUOTE)
    problems = check_archive_provenance(tmp_path, tracked_paths={relative})
    assert problems == [
        f"{relative}: missing replacement (expected one of: Current design, Current replacement, Current sources, Replacement)"
    ]


def test_shape_two_original_path_is_still_tracked_in_the_real_tree() -> None:
    tracked = load_tracked_paths(ROOT)
    assert tracked is not None
    assert (
        original_path_value(line.lstrip("> ") for line in SHAPE_PLAIN_BLOCKQUOTE.splitlines())
        == "docs/perf/freshness-e2e-realpath.md"
    )
    assert "docs/perf/freshness-e2e-realpath.md" in tracked


@pytest.mark.parametrize(
    ("line", "expected"),
    [
        ("> Original path: *docs/perf/a.md*", "docs/perf/a.md"),
        ("- Original location: `docs/plan.md`", "docs/plan.md"),
        ("- Original path: [old](docs/old.md)", "docs/old.md"),
        ("- Reason: nothing here", None),
    ],
)
def test_original_path_value_normalizes_markdown(line: str, expected: str | None) -> None:
    normalized = line.lstrip("> -*").strip()
    assert original_path_value([normalized]) == expected


def test_replacement_is_implied_only_by_a_tracked_original_path(tmp_path: Path) -> None:
    relative = "docs/archive/implied.md"
    header = _complete_header("original_path", "archived_on", "reason", "content_type")
    _write(tmp_path, relative, header)
    assert check_archive_provenance(tmp_path, tracked_paths={relative, "docs/example.md"}) == []
    problems = check_archive_provenance(tmp_path, tracked_paths={relative})
    assert len(problems) == 1
    assert problems[0].startswith(f"{relative}: missing replacement")


def test_main_passing_fixture_prints_ok(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    relative = "docs/archive/ok.md"
    _write(tmp_path, relative, SHAPE_PLAIN_LIST)
    monkeypatch.setattr(
        "scripts.check_archive_provenance.load_tracked_paths",
        lambda root: {relative},
    )
    assert main(["--root", str(tmp_path)]) == 0
    assert capsys.readouterr().out == "archive provenance: OK (1 archived documents)\n"


def test_main_failing_fixture_returns_1(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    relative = "docs/archive/bad.md"
    _write(tmp_path, relative, "# No provenance\n")
    monkeypatch.setattr(
        "scripts.check_archive_provenance.load_tracked_paths",
        lambda root: {relative},
    )
    assert main(["--root", str(tmp_path)]) == 1
    output = capsys.readouterr().out
    assert f"{relative}: missing original_path" in output
    assert "archive provenance: OK" not in output


def test_main_empty_archive_returns_1(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    _write(tmp_path, "docs/archive/README.md", "# Index\n")
    monkeypatch.setattr(
        "scripts.check_archive_provenance.load_tracked_paths",
        lambda root: {"docs/archive/README.md"},
    )
    assert main(["--root", str(tmp_path)]) == 1
    assert "archive provenance: OK" not in capsys.readouterr().out
